package mt

const KER_MATRIX_LOG = `
// Generated by NVIDIA NVVM Compiler
// Compiler built on Thu Mar 13 19:31:35 2014 (1394735495)
// Cuda compilation tools, release 6.0, V6.0.1
//

.version 4.0
.target sm_20
.address_size 64


.visible .entry matrixLog(
	.param .u64 matrixLog_param_0,
	.param .u32 matrixLog_param_1,
	.param .u32 matrixLog_param_2,
	.param .u32 matrixLog_param_3,
	.param .u32 matrixLog_param_4,
	.param .u32 matrixLog_param_5
)
{
	.reg .pred 	%p<12>;
	.reg .s32 	%r<24>;
	.reg .f32 	%f<33>;
	.reg .s64 	%rd<5>;


	ld.param.u64 	%rd3, [matrixLog_param_0];
	ld.param.u32 	%r9, [matrixLog_param_1];
	ld.param.u32 	%r10, [matrixLog_param_2];
	ld.param.u32 	%r11, [matrixLog_param_3];
	ld.param.u32 	%r12, [matrixLog_param_4];
	ld.param.u32 	%r13, [matrixLog_param_5];
	setp.lt.s32	%p1, %r13, 1;
	@%p1 bra 	BB0_10;

	cvta.to.global.u64 	%rd1, %rd3;
	mov.u32 	%r1, %tid.x;
	mov.u32 	%r2, %tid.y;
	mov.u32 	%r14, 0;
	mov.u32 	%r23, %r14;

BB0_2:
	mad.lo.s32 	%r4, %r23, %r9, %r1;
	mov.u32 	%r22, %r14;

BB0_3:
	mov.u32 	%r5, %r22;
	mad.lo.s32 	%r16, %r5, %r10, %r2;
	mad.lo.s32 	%r6, %r16, %r11, %r4;
	setp.lt.s32	%p2, %r6, %r12;
	setp.lt.s32	%p3, %r4, %r11;
	and.pred  	%p4, %p2, %p3;
	@!%p4 bra 	BB0_8;
	bra.uni 	BB0_4;

BB0_4:
	mul.wide.s32 	%rd4, %r6, 4;
	add.s64 	%rd2, %rd1, %rd4;
	ld.global.f32 	%f1, [%rd2];
	setp.gt.f32	%p5, %f1, 0f00000000;
	setp.lt.f32	%p6, %f1, 0f7F800000;
	and.pred  	%p7, %p5, %p6;
	@%p7 bra 	BB0_6;

	lg2.approx.f32 	%f32, %f1;
	bra.uni 	BB0_7;

BB0_6:
	setp.lt.f32	%p8, %f1, 0f00800000;
	mul.f32 	%f7, %f1, 0f4B800000;
	selp.f32	%f8, %f7, %f1, %p8;
	selp.f32	%f9, 0fC3170000, 0fC2FE0000, %p8;
	mov.b32 	 %r17, %f8;
	and.b32  	%r18, %r17, 8388607;
	or.b32  	%r19, %r18, 1065353216;
	mov.b32 	 %f10, %r19;
	shr.u32 	%r20, %r17, 23;
	cvt.rn.f32.u32	%f11, %r20;
	add.f32 	%f12, %f9, %f11;
	setp.gt.f32	%p9, %f10, 0f3FB504F3;
	mul.f32 	%f13, %f10, 0f3F000000;
	add.f32 	%f14, %f12, 0f3F800000;
	selp.f32	%f15, %f13, %f10, %p9;
	selp.f32	%f16, %f14, %f12, %p9;
	add.f32 	%f6, %f15, 0f3F800000;
	add.f32 	%f17, %f15, 0fBF800000;
	// inline asm
	rcp.approx.ftz.f32 %f5,%f6;
	// inline asm
	neg.f32 	%f18, %f17;
	mul.f32 	%f19, %f17, %f18;
	mul.rn.f32 	%f20, %f5, %f19;
	add.rn.f32 	%f21, %f17, %f20;
	mul.f32 	%f22, %f21, %f21;
	mov.f32 	%f23, 0f3C4C4BE0;
	mov.f32 	%f24, 0f3B2063C3;
	fma.rn.f32 	%f25, %f24, %f22, %f23;
	mov.f32 	%f26, 0f3DAAAB50;
	fma.rn.f32 	%f27, %f25, %f22, %f26;
	mul.f32 	%f28, %f27, %f22;
	fma.rn.f32 	%f29, %f28, %f21, %f20;
	add.f32 	%f30, %f29, %f17;
	mov.f32 	%f31, 0f3F317218;
	fma.rn.f32 	%f32, %f16, %f31, %f30;

BB0_7:
	st.global.f32 	[%rd2], %f32;

BB0_8:
	add.s32 	%r7, %r5, 1;
	setp.lt.s32	%p10, %r7, %r13;
	mov.u32 	%r22, %r7;
	@%p10 bra 	BB0_3;

	add.s32 	%r23, %r23, 1;
	setp.lt.s32	%p11, %r23, %r13;
	@%p11 bra 	BB0_2;

BB0_10:
	ret;
}`
