package mt

const KER_MATRIX_MULT = `
//
// Generated by NVIDIA NVVM Compiler
// Compiler built on Thu Mar 13 19:31:35 2014 (1394735495)
// Cuda compilation tools, release 6.0, V6.0.1
//

.version 4.0
.target sm_20
.address_size 64


.visible .entry matrixMul(
	.param .u64 matrixMul_param_0,
	.param .u64 matrixMul_param_1,
	.param .u64 matrixMul_param_2,
	.param .u32 matrixMul_param_3,
	.param .u32 matrixMul_param_4,
	.param .u32 matrixMul_param_5,
	.param .u32 matrixMul_param_6,
	.param .u32 matrixMul_param_7,
	.param .u32 matrixMul_param_8
)
{
	.reg .pred 	%p<7>;
	.reg .s32 	%r<28>;
	.reg .f32 	%f<2>;
	.reg .s64 	%rd<13>;
	.reg .f64 	%fd<10>;


	ld.param.u64 	%rd4, [matrixMul_param_0];
	ld.param.u64 	%rd5, [matrixMul_param_1];
	ld.param.u64 	%rd6, [matrixMul_param_2];
	ld.param.u32 	%r13, [matrixMul_param_3];
	ld.param.u32 	%r14, [matrixMul_param_4];
	ld.param.u32 	%r15, [matrixMul_param_5];
	ld.param.u32 	%r16, [matrixMul_param_6];
	ld.param.u32 	%r17, [matrixMul_param_8];
	setp.lt.s32	%p1, %r17, 1;
	@%p1 bra 	BB0_11;

	cvta.to.global.u64 	%rd1, %rd4;
	cvta.to.global.u64 	%rd2, %rd6;
	cvta.to.global.u64 	%rd3, %rd5;
	mul.lo.s32 	%r1, %r16, %r15;
	mov.u32 	%r2, %tid.y;
	mov.u32 	%r18, 0;
	mov.u32 	%r26, %r18;

BB0_2:
	mov.u32 	%r20, %tid.x;
	mad.lo.s32 	%r4, %r26, %r15, %r20;
	mov.u32 	%r25, %r18;

BB0_3:
	mov.u32 	%r5, %r25;
	mad.lo.s32 	%r6, %r5, %r16, %r2;
	mad.lo.s32 	%r7, %r6, %r14, %r4;
	setp.ge.s32	%p2, %r7, %r1;
	@%p2 bra 	BB0_9;

	setp.gt.s32	%p3, %r13, 0;
	@%p3 bra 	BB0_6;

	mov.f64 	%fd9, 0d0000000000000000;
	bra.uni 	BB0_8;

BB0_6:
	mul.lo.s32 	%r8, %r6, %r13;
	mov.f64 	%fd9, 0d0000000000000000;
	mov.u32 	%r27, 0;

BB0_7:
	add.s32 	%r22, %r27, %r8;
	mul.wide.s32 	%rd7, %r22, 8;
	add.s64 	%rd8, %rd3, %rd7;
	mad.lo.s32 	%r23, %r27, %r14, %r4;
	mul.wide.s32 	%rd9, %r23, 8;
	add.s64 	%rd10, %rd2, %rd9;
	ld.global.f64 	%fd6, [%rd10];
	ld.global.f64 	%fd7, [%rd8];
	fma.rn.f64 	%fd8, %fd7, %fd6, %fd9;
	cvt.rn.f32.f64	%f1, %fd8;
	cvt.f64.f32	%fd9, %f1;
	add.s32 	%r27, %r27, 1;
	setp.lt.s32	%p4, %r27, %r13;
	@%p4 bra 	BB0_7;

BB0_8:
	mul.wide.s32 	%rd11, %r7, 8;
	add.s64 	%rd12, %rd1, %rd11;
	st.global.f64 	[%rd12], %fd9;

BB0_9:
	add.s32 	%r11, %r5, 1;
	setp.lt.s32	%p5, %r11, %r17;
	mov.u32 	%r25, %r11;
	@%p5 bra 	BB0_3;

	add.s32 	%r26, %r26, 1;
	setp.lt.s32	%p6, %r26, %r17;
	@%p6 bra 	BB0_2;

BB0_11:
	ret;
}`
