package mt

const KER_MATRIX_ADD_BIAS = `
//
// Generated by NVIDIA NVVM Compiler
// Compiler built on Thu Mar 13 19:31:35 2014 (1394735495)
// Cuda compilation tools, release 6.0, V6.0.1
//

.version 4.0
.target sm_20
.address_size 64


.visible .entry matrixAddBias(
	.param .u64 matrixAddBias_param_0,
	.param .u64 matrixAddBias_param_1,
	.param .u32 matrixAddBias_param_2,
	.param .u32 matrixAddBias_param_3,
	.param .u32 matrixAddBias_param_4,
	.param .u32 matrixAddBias_param_5,
	.param .u32 matrixAddBias_param_6
)
{
	.reg .pred 	%p<8>;
	.reg .s32 	%r<24>;
	.reg .f32 	%f<2>;
	.reg .s64 	%rd<9>;


	ld.param.u64 	%rd4, [matrixAddBias_param_0];
	ld.param.u64 	%rd5, [matrixAddBias_param_1];
	ld.param.u32 	%r9, [matrixAddBias_param_2];
	ld.param.u32 	%r10, [matrixAddBias_param_3];
	ld.param.u32 	%r11, [matrixAddBias_param_4];
	ld.param.u32 	%r12, [matrixAddBias_param_5];
	ld.param.u32 	%r13, [matrixAddBias_param_6];
	setp.lt.s32	%p1, %r13, 1;
	@%p1 bra 	BB0_9;

	cvta.to.global.u64 	%rd1, %rd5;
	cvta.to.global.u64 	%rd2, %rd4;
	mov.u32 	%r1, %tid.x;
	mov.u32 	%r2, %tid.y;
	mov.u32 	%r14, 0;
	mov.u32 	%r23, %r14;

BB0_2:
	mad.lo.s32 	%r4, %r23, %r9, %r1;
	mov.u32 	%r22, %r14;

BB0_3:
	mov.u32 	%r5, %r22;
	mad.lo.s32 	%r16, %r5, %r10, %r2;
	mad.lo.s32 	%r6, %r16, %r11, %r4;
	setp.lt.s32	%p2, %r6, %r12;
	setp.lt.s32	%p3, %r4, %r11;
	and.pred  	%p4, %p2, %p3;
	@!%p4 bra 	BB0_7;
	bra.uni 	BB0_4;

BB0_4:
	setp.eq.s32	%p5, %r4, 0;
	mul.wide.s32 	%rd6, %r6, 4;
	add.s64 	%rd3, %rd2, %rd6;
	@%p5 bra 	BB0_6;

	div.s32 	%r17, %r6, %r11;
	add.s32 	%r18, %r6, -1;
	sub.s32 	%r19, %r18, %r17;
	mul.wide.s32 	%rd7, %r19, 4;
	add.s64 	%rd8, %rd1, %rd7;
	ld.global.f32 	%f1, [%rd8];
	st.global.f32 	[%rd3], %f1;
	bra.uni 	BB0_7;

BB0_6:
	mov.u32 	%r20, 1065353216;
	st.global.u32 	[%rd3], %r20;

BB0_7:
	add.s32 	%r7, %r5, 1;
	setp.lt.s32	%p6, %r7, %r13;
	mov.u32 	%r22, %r7;
	@%p6 bra 	BB0_3;

	add.s32 	%r23, %r23, 1;
	setp.lt.s32	%p7, %r23, %r13;
	@%p7 bra 	BB0_2;

BB0_9:
	ret;
}`
