package mt

const KER_MATRIX_SUM_ALL = `
//
// Generated by NVIDIA NVVM Compiler
// Compiler built on Thu Mar 13 19:31:35 2014 (1394735495)
// Cuda compilation tools, release 6.0, V6.0.1
//

.version 4.0
.target sm_20
.address_size 64

// matrixSumAll$__cuda_local_var_34142_32_non_const_res has been demoted

.visible .entry matrixSumAll(
	.param .u64 matrixSumAll_param_0,
	.param .u32 matrixSumAll_param_1,
	.param .u32 matrixSumAll_param_2,
	.param .u64 matrixSumAll_param_3
)
{
	.reg .pred 	%p<6>;
	.reg .s32 	%r<17>;
	.reg .f32 	%f<32>;
	.reg .s64 	%rd<17>;
	// demoted variable
	.shared .align 4 .b8 matrixSumAll$__cuda_local_var_34142_32_non_const_res[4096];

	ld.param.u64 	%rd8, [matrixSumAll_param_0];
	ld.param.u32 	%r9, [matrixSumAll_param_1];
	ld.param.u32 	%r10, [matrixSumAll_param_2];
	ld.param.u64 	%rd9, [matrixSumAll_param_3];
	mov.u32 	%r1, %tid.x;
	mul.wide.u32 	%rd10, %r1, 4;
	mov.u64 	%rd16, matrixSumAll$__cuda_local_var_34142_32_non_const_res;
	add.s64 	%rd1, %rd16, %rd10;
	mov.u32 	%r16, 0;
	st.shared.u32 	[%rd1], %r16;
	setp.lt.s32	%p1, %r9, 1;
	@%p1 bra 	BB0_5;

	cvta.to.global.u64 	%rd12, %rd8;
	mul.lo.s32 	%r14, %r1, %r9;
	mul.wide.s32 	%rd13, %r14, 4;
	add.s64 	%rd15, %rd12, %rd13;
	mov.f32 	%f30, 0f00000000;
	mov.u32 	%r15, 0;

BB0_2:
	setp.ge.s32	%p2, %r14, %r10;
	@%p2 bra 	BB0_4;

	ld.global.f32 	%f8, [%rd15];
	add.f32 	%f30, %f30, %f8;
	st.shared.f32 	[%rd1], %f30;

BB0_4:
	add.s64 	%rd15, %rd15, 4;
	add.s32 	%r14, %r14, 1;
	add.s32 	%r15, %r15, 1;
	setp.lt.s32	%p3, %r15, %r9;
	@%p3 bra 	BB0_2;

BB0_5:
	bar.sync 	0;
	setp.ne.s32	%p4, %r1, 0;
	@%p4 bra 	BB0_9;

	cvta.to.global.u64 	%rd5, %rd9;
	ld.shared.f32 	%f31, [matrixSumAll$__cuda_local_var_34142_32_non_const_res];

BB0_7:
	ld.shared.f32 	%f9, [%rd16+4];
	add.f32 	%f10, %f31, %f9;
	ld.shared.f32 	%f11, [%rd16+8];
	ld.shared.f32 	%f12, [%rd16+12];
	ld.shared.f32 	%f13, [%rd16+16];
	st.shared.f32 	[matrixSumAll$__cuda_local_var_34142_32_non_const_res], %f10;
	add.f32 	%f14, %f10, %f11;
	st.shared.f32 	[matrixSumAll$__cuda_local_var_34142_32_non_const_res], %f14;
	add.f32 	%f15, %f14, %f12;
	st.shared.f32 	[matrixSumAll$__cuda_local_var_34142_32_non_const_res], %f15;
	add.f32 	%f16, %f15, %f13;
	st.shared.f32 	[matrixSumAll$__cuda_local_var_34142_32_non_const_res], %f16;
	ld.shared.f32 	%f17, [%rd16+20];
	add.f32 	%f18, %f16, %f17;
	ld.shared.f32 	%f19, [%rd16+24];
	ld.shared.f32 	%f20, [%rd16+28];
	ld.shared.f32 	%f21, [%rd16+32];
	st.shared.f32 	[matrixSumAll$__cuda_local_var_34142_32_non_const_res], %f18;
	add.f32 	%f22, %f18, %f19;
	st.shared.f32 	[matrixSumAll$__cuda_local_var_34142_32_non_const_res], %f22;
	add.f32 	%f23, %f22, %f20;
	st.shared.f32 	[matrixSumAll$__cuda_local_var_34142_32_non_const_res], %f23;
	add.f32 	%f24, %f23, %f21;
	st.shared.f32 	[matrixSumAll$__cuda_local_var_34142_32_non_const_res], %f24;
	ld.shared.f32 	%f25, [%rd16+36];
	add.f32 	%f26, %f24, %f25;
	ld.shared.f32 	%f27, [%rd16+40];
	ld.shared.f32 	%f28, [%rd16+44];
	st.shared.f32 	[matrixSumAll$__cuda_local_var_34142_32_non_const_res], %f26;
	add.f32 	%f29, %f26, %f27;
	st.shared.f32 	[matrixSumAll$__cuda_local_var_34142_32_non_const_res], %f29;
	add.s64 	%rd16, %rd16, 44;
	add.f32 	%f31, %f29, %f28;
	st.shared.f32 	[matrixSumAll$__cuda_local_var_34142_32_non_const_res], %f31;
	add.s32 	%r16, %r16, 11;
	setp.ne.s32	%p5, %r16, 1023;
	@%p5 bra 	BB0_7;

	st.global.f32 	[%rd5], %f31;

BB0_9:
	ret;
}`
